# Digital Forms API for VIPS-ICBC integration for immediate roadside prohibition (DFAPI-VIIRP)
# Exploratory testing
# See code at: https://github.com/bcgov/jag-rsbc-digital-forms-viirp-integration
# Documentation:
# High level design:
#  - https://justice.gov.bc.ca/wiki/pages/viewpage.action?pageId=343835390
# Requirements document:
#  - https://justice.gov.bc.ca/wiki/download/attachments/343835390/IRP-VI%20Interfaces%2031Mar22.estimate%20removed.docx?version=1&modificationDate=1653673345000&api=v2
#
#  - https://justice.gov.bc.ca/wiki/display/RDFP/VIPS+integration
#
# FOLLOW SERVICE LOGS:
# oc --namespace=c220ad-dev logs svc/digitalforms-viirp-api-svc --follow
# oc --namespace=c220ad-test logs svc/digitalforms-viirp-api-svc --follow


### OpenAPI specification
GET https://{{host}}{{api_path}}/v3/api-docs

### ORDS Healthcheck
GET https://{{host}}{{api_path}}/utility/ords/ping/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}


###   ____          _        _        _     _
###  / ___|___   __| | ___  | |_ __ _| |__ | | ___  ___
### | |   / _ \ / _` |/ _ \ | __/ _` | '_ \| |/ _ \/ __|
### | |__| (_) | (_| |  __/ | || (_| | |_) | |  __/\__ \
###  \____\___/ \__,_|\___|  \__\__,_|_.__/|_|\___||___/

### Code tables
GET https://{{host}}{{api_path}}/codetables/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Accept: application/json



###  ____            _     _ _     _  _  _
### |  _ \ _ __ ___ | |__ (_) |__ (_) |_(_) ___  _ __  ___
### | |_) | '__/ _ \| '_ \| | '_ \| | __| |/ _ \| '_ \/ __|
### |  __/| | | (_) | | | | | |_) | | |_| | (_) | | | \__ \
### |_|   |_|  \___/|_| |_|_|_.__/|_|\__|_|\___/|_| |_|___/

### Prohibitions GET /prohibitions/<prohibition>/<correlation>
GET https://{{host}}{{api_path}}/prohibitions/20100160/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Accept: application/json

### Prohibitions OPTIONS /prohibitions/<prohibition>/<correlation>
OPTIONS https://{{host}}{{api_path}}/prohibitions/20100160/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Accept: application/json

### Prohibitions HEAD /prohibitions/<prohibition>/<correlation>
HEAD https://{{host}}{{api_path}}/prohibitions/20100160/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Accept: application/json



### Prohibitions POST IRP /prohibitions/<correlation>
# Look it up in VIPS here: https://dev.justice.gov.bc.ca/vips/prohibitions/
POST https://{{host}}{{api_path}}/prohibitions/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Content-Type: application/json

{
  "vipsDocumentIdArray": [
  ],
  "vipsProhibitionCreate": {
    "cityNm":                 "Ashcroft",
    "dreEvaluationCds":       [],
    "driverLicenceSeizedYN":  "Y",
    "effectiveDt":            "2022-09-27T00:10:00.000-07:00",
    "expiryDt":               null,
    "incidentDtm":            "2022-09-27T00:01:00.000-07:00",
    "noticeServedDt":         "2022-09-27T00:10:00.000-07:00",
    "noticeSubjectCd":        "PERS",
    "noticeTypeCd":           "IRP",:
    "originalCauseCd":        "IRPINDEF",
    "policeDetatchmentId":    138,
    "policeFileNo":           "RSI-1234",
    "policeOfficerNm":        "Lungpayne",
    "policeOfficerNo":        "RSI111",
    "prohibitionNoticeNo":    "20100161",
    "provinceCd":             "BC",
    "streetDetailsTxt":       "ANT AVE @ LAMA LANE",
    "tempDlEffectiveDt":      null,
    "tempDlExpiryDt":         null
  },
  "vipsRegistrationCreate": {
    "dataSourceCd":           "ICBC",
    "firstGivenNm":           "Davey",
    "icbcEnterpriseId":       "1",
    "organizationNm":         null,
    "registrationRoleCd":     "DRVR",
    "secondGivenNm":          "Damien",
    "surnameNm":              "Dogsneeze",
    "thirdGivenNm":           "Dinglebert",
    "vipsAddressArray": [
      {
        "additionalDeliveryLineTxt":  null,
        "addressFirstLineTxt":        "425 Tiwje View",
        "addressSecondLineTxt":       "Sludge Manor",
        "addressThirdLineTxt":        "Basement Suite",
        "cityNm":                     "Ashcroft",
        "countryNm":                  "CAN",
        "postalCodeTxt":              "S8Q 2B2",
        "provinceCd":                 "BC",
        "registrationAddressTypeCd":  "MAIL"
      }
    ],
    "vipsLicenceCreateObj": {
      "birthDt":              "1975-01-01T00:00:00.000-08:00",
      "dlJurisdictionCd":     "BC",
      "driverLicenceNo":      "1975001"
    }
  }
}

###
# Defects:
# - Time zone issue in birth date field
# - If country is "CA" not "CAD", API returns 500.


### Prohibitions POST VI
POST https://{{host}}{{api_path}}/prohibitions/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Content-Type: application/json

{
  "vipsDocumentIdArray": [
  ],
  "vipsProhibitionCreate": {
    "cityNm": "Ashcroft",
    "dreEvaluationCds": [],
    "driverLicenceSeizedYN": "Y",
    "effectiveDt": "2022-09-27T12:43:00.000-07:00",
    "expiryDt": null,
    "incidentDtm":    "2022-09-27T12:43:00.000-07:00",
    "noticeServedDt": "2022-09-27T12:48:46.000-07:00",
    "noticeSubjectCd": "PERS",
    "noticeTypeCd": "IRP",
    "originalCauseCd": "IRPINDEF",
    "policeDetatchmentId": 140,
    "policeFileNo": "RSI-1234",
    "policeOfficerNm": "Lungpayne",
    "policeOfficerNo": "RSI111",
    "prohibitionNoticeNo": "99100953",
    "provinceCd": "BC",
    "streetDetailsTxt": "ANT AVE / LAMA LANE",
    "tempDlEffectiveDt": null,
    "tempDlExpiryDt": null
  },
  "vipsRegistrationCreate": {
    "dataSourceCd": "ICBC",
    "firstGivenNm": "Davey",
    "icbcEnterpriseId": "1",
    "organizationNm": null,
    "registrationRoleCd": "DRVR",
    "secondGivenNm": null,
    "surnameNm": "Dogsneeze",
    "thirdGivenNm": null,
    "vipsAddressArray": [
      {
        "additionalDeliveryLineTxt": null,
        "addressFirstLineTxt": "425 Tiwje View",
        "addressSecondLineTxt": null,
        "addressThirdLineTxt": null,
        "cityNm": "Ashcroft",
        "countryNm": "CAN",
        "postalCodeTxt": "S8Q2B2",
        "provinceCd": "BC",
        "registrationAddressTypeCd": "MAIL"
      }
    ],
    "vipsLicenceCreateObj": {
      "birthDt": "1960-08-11T00:00:00.000-07:00",
      "dlJurisdictionCd": "BC",
      "driverLicenceNo": "1234567"
    }
  }
}

### Prohibitions OPTIONS /prohibitions/<correlation>
# OPTIONS method returns info about API (methods/content type)
# Look for "allow" header in repsponse. For example "allow: POST,OPTIONS"
OPTIONS https://{{host}}{{api_path}}/prohibitions/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Accept: application/json

### Prohibitions HEAD /prohibitions/<correlation>
# HEAD method returns info about resource (version/length/type)
HEAD https://{{host}}{{api_path}}/prohibitions/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Accept: application/json



### DF payloads
@noticeNo = 00011122
GET https://{{host}}{{api_path}}/dfpayloads/{{noticeNo}}/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Accept: application/json

### Shaun's example
POST https://{{host}}{{api_path}}/prohibitions/steve-test-{{$uuid}}
Authorization: Basic {{api_username}} {{api_password}}
Content-Type: application/json

{
  "vipsProhibitionCreate": {
    "cityNm":                 "VICTORIA",
    "driverLicenceSeizedYN":  "N",
    "dreEvaluations":         [],
    "effectiveDt":            "2018-10-11T00:00:00.000-07:00",
    "expiryDt":               null,
    "incidentDtm":            "2018-11-05T00:00:00.000-07:00",
    "noticeServedDt":         "2018-10-07T00:00:00.000-07:00",
    "noticeSubjectCd":        "PERS",
    "noticeTypeCd":           "IRP",
    "originalCauseCd":        "IRPINDEF",
    "policeDetatchmentId":    304,
    "policeFileNo":           "802",
    "policeOfficerNm":        "Police Officer Jones",
    "policeOfficerNo":        "420",
    "prohibitionNoticeNo":    20100146,
    "provinceCd": "BC",
    "streetDetailsTxt": "Some street details",
    "tempDlEffectiveDt": null,
    "tempDlExpiryDt": null
  },
  "vipsRegistrationCreate": {
    "dataSourceCd": "ICBC",
    "firstGivenNm": "Jeffery",
    "icbcEnterpriseId": "1",
    "organizationNm": null,
    "registrationRoleCd": "DRVR",
    "secondGivenNm": "Michael",
    "surnameNm": "Gordon",
    "thirdGivenNm": null,
    "vipsAddressArray": [
      {
        "additionalDeliveryLineTxt": null,
        "addressFirstLineTxt": "2018 Warner Bros. Pl",
        "addressSecondLineTxt": null,
        "addressThirdLineTxt": null,
        "cityNm": "Burbank",
        "countryNm": "USA",
        "postalCodeTxt": "96321",
        "provinceCd": "CA",
        "registrationAddressTypeCd": "MAIL"
      }
    ],
    "vipsLicenceCreateObj": {
      "birthDt": "1971-04-08T00:00:00.000-07:00",
      "driverLicenceNo": "6400717",
      "dlJurisdictionCd": "BC"
    }
  },
  "vipsDocumentIdArray": [
  ]
}